# send to container based infrastructure: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  directories:
  - $HOME/.m2
  - datasets

language: java

after_success:
  - mvn clean cobertura:cobertura coveralls:report