# send to container based infrastructure: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  directories:
  - $HOME/.m2
  - datasets

language: java

install: true

script: mvn clean test jacoco:report

after_success:
  - mvn coveralls:report