# send to container based infrastructure: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  directories:
  - $HOME/.m2
  - datasets

language: java

install: echo 'Skipping mvn install'

script:
   - mvn test
#  - mvn test -P coveralls

#after_script:
#  - mvn jacoco:report coveralls:report -P coveralls